project_id = "ubzrshboajvdsztgptsk"

[functions.notify-telegram]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.payment-init]
verify_jwt = false

[functions.ziraat-payment-init]
verify_jwt = false

[functions.ziraat-payment-verify]
verify_jwt = false
