project_id = "ubzrshboajvdsztgptsk"

[functions.notify-telegram]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.payment-init]
verify_jwt = false

[functions.payment-mock-verify]
verify_jwt = false

[functions.payment-config-check]
verify_jwt = false
